### ISSUE TITLE
Travis와 관련된 ISSUE

### ISSUE THREAD

**Issue by mjin1220** [AJOU-Connection/StopBus_User#1]
```sh
$ ./gradlew build connectedCheck
/home/travis/.travis/job_stages: line 57: ./gradlew: Permission denied
The command "./gradlew build connectedCheck" exited with 126.
Done. Your build exited with 1.
```
위의 에러 메세지는 travis #7에서 발생한 것입니다. 
권한 문제는 아래와 같이 코드를 추가하여 해결했습니다.
https://github.com/Danbk93/StopBus_User/blob/d4fa555c5e26f82beefa792166072980c81c58e7/.travis.yml#L5-L8

하지만 아래와 같이 Build Failed Error가 여전히 발생합니다. 이와 관련되어 해결부탁드립니다.
```sh
WARNING: Configuration 'compile' is obsolete and has been replaced with 'implementation' and 'api'.
It will be removed at the end of 2018. For more information see: http://d.android.com/r/tools/update-dependency-configurations.html
WARNING: The specified Android SDK Build Tools version (26.0.2) is ignored, as it is below the minimum supported version (27.0.3) for Android Gradle Plugin 3.1.1.
Android SDK Build Tools 27.0.3 will be used.
To suppress this warning, remove "buildToolsVersion '26.0.2'" from your build.gradle file, as each version of the Android Gradle Plugin now has a default version of the build tools.
File /home/travis/.android/repositories.cfg could not be loaded.
Checking the license for package Android SDK Build-Tools 27.0.3 in /usr/local/android-sdk/licenses
Warning: License for package Android SDK Build-Tools 27.0.3 not accepted.
FAILURE: Build failed with an exception.
* What went wrong:
A problem occurred configuring project ':app'.
> Failed to install the following Android SDK packages as some licences have not been accepted.
     build-tools;27.0.3 Android SDK Build-Tools 27.0.3
  To build this project, accept the SDK license agreements and install the missing components using the Android Studio SDK Manager.
  Alternatively, to transfer the license agreements from one workstation to another, see http://d.android.com/r/studio-ui/export-licenses.html
  
  Using Android SDK: /usr/local/android-sdk
* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
* Get more help at https://help.gradle.org
BUILD FAILED in 42s
The command "./gradlew build connectedCheck" exited with 1.
Done. Your build exited with 1.
```

**Comment by Danbk93** [comment]
Build tools 버전이 맞지 않아 생기는 오류입니다. 기존 SDK Bulid Tools version을 26.0.2에서 27.0.3 버전으로 변경 하여서 문제 해결 하였습니다.
```
env:
  global:
   - ANDROID_API_LEVEL=26
   - ANDROID_BUILD_TOOLS_VERSION=27.0.3
   - EMULATOR_API_LEVEL=21

android:
  components:
    - tools
    - platform-tools
    - tools
    
    # The BuildTools version used by your project
    - build-tools-$ANDROID_BUILD_TOOLS_VERSION
```
